jsschema = require('./jsschema.js')

schema = jsschema.schema;
required = jsschema.required;
optional = jsschema.optional;
repeated = jsschema.repeated;


student = schema(function() {
	this.name = required("string");
	this.age = required("number");

	this.parent = optional(this);

	this.goodBirthdays = repeated("number");
	this.friends = repeated(this);
});

peter = {
	name: "Peter",
	age: 14,
	parent: null,
	goodBirthdays: [],
	friends: []
};

john = {
	name: "John",
	parent: null,
	goodBirthdays: [],
	friends: []
};

jack = {
	name: "Jack",
	age: "10",
	parent: null,
	goodBirthdays: [],
	friends: []
};

jim = {
	name: "Jim",
	age: 10,
	parent: null,
	goodBirthdays: [],
	friends: [{ name: "Joseph" }]
};

jake = {
	name: "Jim",
	age: 10,
	parent: null,
	goodBirthdays: [],
	friends: {}
};


throwsLogged = function(test, block) {
	try {
		block();
	} catch (e) {
		console.log(e);
		test.throws(block);
	}
}

exports['normal case'] = function(test) {
	test.ok(jsschema.check(student, peter));
	test.strictEqual(jsschema.valid(student, peter), true);
	test.done();
};

exports['field missing: age'] = function(test) {
	throwsLogged(test, function(){ jsschema.check(student, john) });
	test.strictEqual(jsschema.valid(student, john), false);
	test.done();
};

exports['wrong type: age'] = function(test) {
	throwsLogged(test, function(){ jsschema.check(student, jack) });
	test.strictEqual(jsschema.valid(student, jack), false);
	test.done();
};

exports['repeated field has entry with wrong structure: friends'] = function(test) {
	throwsLogged(test, function(){ jsschema.check(student, jake) });
	test.strictEqual(jsschema.valid(student, jake), false);
	test.done();
};

exports['repeated field is not an array: friends'] = function(test) {
	throwsLogged(test, function(){ jsschema.check(student, jim) });
	test.strictEqual(jsschema.valid(student, jim), false);
	test.done();
};


teacher = schema(function() {
	this.fav = optional(student);
	this.affair = optional(this);
});

mrGarrison = {
	fav: peter
}

someOtherTeacher = {
	fav: peter,
	affair: mrGarrison
}

exports['recursive type optional field not set'] = function(test) {
	test.ok(jsschema.check(teacher, mrGarrison));
	test.strictEqual(jsschema.valid(teacher, mrGarrison), true);
	test.done();
};

exports['recursive type optional field set'] = function(test) {
	test.ok(jsschema.check(teacher, someOtherTeacher));
	test.strictEqual(jsschema.valid(teacher, someOtherTeacher), true);
	test.done();
};


// generated by coffee-script's "class"
schema(CSteacher = (function() {
	function CSteacher() {}
	CSteacher.fav = optional(student);
	CSteacher.affair = optional(CSteacher);
	return CSteacher;
})());

CSmrGarrison = {
	fav: peter
}

CSsomeOtherTeacher = {
	fav: peter,
	affair: mrGarrison
}

exports['(coffe-script class generated) recursive type optional field not set'] = function(test) {
	test.ok(jsschema.check(CSteacher, CSmrGarrison));
	test.strictEqual(jsschema.valid(teacher, CSmrGarrison), true);
	test.done();
};

exports['(coffe-script class generated) recursive type optional field set'] = function(test) {
	test.ok(jsschema.check(CSteacher, CSsomeOtherTeacher));
	test.strictEqual(jsschema.valid(teacher, CSsomeOtherTeacher), true);
	test.done();
};


exports['recursive required fields are forbidden'] = function(test) {
	throwsLogged(test, function() {
		requiredRecursiveSchema = schema(function() {
			this.other = required(this);
		});
	});
	test.done();
};

